# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test3():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_3(self):
        self.driver.get("https://the-internet.herokuapp.com/javascript_alerts")
        self.driver.set_window_size(1106, 1020)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1) > button").click()

    def test_4(self):
        self.driver.get("https://the-internet.herokuapp.com/javascript_alerts")
        self.driver.set_window_size(1106, 1020)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) > button").click()

    def test_u(self):
        self.driver.get("https://the-internet.herokuapp.com/javascript_alerts")
        self.driver.set_window_size(1106, 1020)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) > button").click()
        assert self.driver.switch_to.alert.text == "I am a JS prompt"
        alert = self.driver.switch_to.alert
        alert.send_keys("test")
        alert.accept()